
<?php
	if(!$this->view->noticia){
		header('Location: /');
	}
?>


<section id="alter">
	<form action="/alter-crud" method="POST">
		<input type="text" name="titulo" placeholder="Titulo da noticia" value="<?=$this->view->noticia['titulo']?>">
		<input style="display: none;" type="text" name="id" value="<?=$this->view->noticia['id']?>">
		<textarea name="noticia"><?=$this->view->noticia['noticia']?></textarea>
		<input type="submit" value="Enviar">
	</form>
</section>
